baseURL: http://example.org/
languageCode: en-us
title: m-fra.me
theme: m-fra.me

params:
  tagline: "A structure for my continued education"

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1

    - identifier: About
      name: About
      url: /about/
      weight: 2

    - identifier: Resume
      name: Resume
      url: /resume/
      weight: 2
